### ISSUE TITLE
Parsing new line characters

### ISSUE THREAD

**Issue by rraabe** [mvayngrib/parse-usdl#18]
I'm working with the L-Tron LTC4910 scanner in the USB Keyboard mode. When scanning a driver's license I get a string formatted as below:

`@
ANSI 636024070001DL00310247DLDAQ12345678DCSDOEDDENDACJANEDDFNDADCDDGUDCADDCBNONEDCDNONEDBD02012018DBB01011940DBA01012022DBC2DAU070 inDAYHAZDAG10 SOME STREETDAICITYDAJVTDAK123450000  DCF123451234544DCGUSADAW170DAHNONEDDAFDDB02202013DDK1`

The only new line characters are after the `@` and `ANSI`. If I manually add new lines after each section, the string parses but if I don't, the string returns an empty object. I believe the prefixes are different for each state so I'm unsure of how to parse the string programmatically. Is there a way to parse the data without requiring the new line characters?

Thanks for the help.

**Comment by mvayngrib** [comment]
@rraabe the main problem is that every state implements the spec differently and we don't have an exhaustive list of codes (DLD, DAG etc). This makes parsing without line breaks a guessing game :)

**Comment by rraabe** [comment]
That was what I thought. I'll give L-Tron a call to see if I can retain the line breaks when scanning. Thanks for the quick response.

**Comment by rraabe** [comment]
In case anyone finds this thread. I put a onKeyDown event listener on my input and scanned the license. I found out that the scanner was using a combination of ArrowDown and then Shift to denote new line characters. I was able to parse that combination into actual new line characters and the parsing library works as intended.
